import type { Metadata } from "next";
import "./globals.css";
import { QueryClientProvider } from "./query-clien-provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import localFont from "next/font/local";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import {Questions} from "@/components/layout/questioins";
import { auth } from "@/server/auth/auth";
import {headers as nextHeaders} from "next/headers"
import { Unbounded } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";


const sfPro = localFont({
  src: [
    {
      path: "../../public/fonts/SFPro_Text_Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/SFPro_Text_Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/SFPro_Text_Semibold.otf",
      weight: "600",
      style: "normal",
    },

  ],
  variable: "--font-sfpro",
});

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-unbounded",  
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
      headers: await nextHeaders()
  
    });
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", sfPro.variable, "font-sans",unbounded.variable,  "bg-white-component")}
    >
      <body className="min-h-full flex flex-col relative">
        <QueryClientProvider>
          
          <Toaster richColors/>
          <TooltipProvider>
            <Header/>
            {children}
            <Questions/>
            <Footer/>
          </TooltipProvider>
          
        </QueryClientProvider>  
      </body>
    </html>
  );
}
